# Generated by Django 4.2.5 on 2023-11-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
